config/routes.rb
Rails.application.routes.draw do
  get 'requests/tables/:table_id', to: 'requests#table_requests', as: 'table_requests'
  get 'items/menus/:menu_id', to: 'items#items_by_menu', as: 'menu_items'
  get 'tables/:id/bill', to: 'tables#generate_bill', as: 'generate_bill'
  post 'tables/waiters/', to:  'tables#waiter_exists', as: 'waiter_exists'
  resources :waiters
  resources :tables do
    get '/bill', to: 'tables#generate_bill', as: 'generate_bill'
  end
  resources :items
  resources :menus
  resources :requests do
    patch '/amounts', to: 'requests#create_amounts'
    get '/amounts/all', to: 'requests#find_amounts'
    delete '/amounts/:id/delete', to: 'requests#delete_amount'
  end
  resources :customers
  devise_for :users
  root 'tables#index'
end

app/models/menu.rb
class Menu < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:name)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= simple_form_for(@menu) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container bg-dark cont">
  <div class="row">
    <div class="col-sm-10 offset-sm-1">
      <h1 class="display-4 text-white"> Cardápios </h1>

      <table class="table table-striped table-hover table-light mt-3">
        <thead>
          <tr>
            <th>Nome</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @menus.each do |menu| %>
            <tr>
              <td><%= menu.name %></td>
              <td><%= link_to menu, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
                <i class="far fa-trash-alt"></i>
              <%end%>
              &nbsp;
              <%= link_to edit_menu_path(menu), class: "btn btn-primary" do %>
                <i class="far fa-edit"></i>
              <%end%>
              &nbsp;
              <%= link_to menu_path(menu), class: "btn btn-success" do %>
                <i class="far fa-eye"></i>
              <%end%>
              &nbsp;
              <%= link_to menu_items_path(menu), class: "btn btn-default" do %>
                <i class="fas fa-utensils"></i>
              <%end%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Novo Cardápio', new_menu_path(), class: "btn btn-info" %>
    </div>
  </div>
</div>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= @menu.name %></p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>