config/routes.rb
Rails.application.routes.draw do
  get 'requests/tables/:table_id', to: 'requests#table_requests', as: 'table_requests'
  get 'items/menus/:menu_id', to: 'items#items_by_menu', as: 'menu_items'
  get 'tables/:id/bill', to: 'tables#generate_bill', as: 'generate_bill'
  post 'tables/waiters/', to:  'tables#waiter_exists', as: 'waiter_exists'
  resources :waiters
  resources :tables do
    get '/bill', to: 'tables#generate_bill', as: 'generate_bill'
  end
  resources :items
  resources :menus
  resources :requests do
    patch '/amounts', to: 'requests#create_amounts'
    get '/amounts/all', to: 'requests#find_amounts'
    delete '/amounts/:id/delete', to: 'requests#delete_amount'
  end
  resources :customers
  devise_for :users
  root 'tables#index'
end

app/models/waiter.rb
class Waiter < ApplicationRecord
    has_many :tables
end

app/controllers/waiters_controller.rb
class WaitersController < ApplicationController
  before_action :set_waiter, only: [:show, :edit, :update, :destroy]

  # GET /waiters
  # GET /waiters.json
  def index
    @waiters = Waiter.all
  end

  # GET /waiters/1
  # GET /waiters/1.json
  def show
  end

  # GET /waiters/new
  def new
    @waiter = Waiter.new
  end

  # GET /waiters/1/edit
  def edit
  end

  # POST /waiters
  # POST /waiters.json
  def create
    @waiter = Waiter.new(waiter_params)

    respond_to do |format|
      if @waiter.save
        format.html { redirect_to @waiter, notice: 'Waiter was successfully created.' }
        format.json { render :show, status: :created, location: @waiter }
      else
        format.html { render :new }
        format.json { render json: @waiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waiters/1
  # PATCH/PUT /waiters/1.json
  def update
    respond_to do |format|
      if @waiter.update(waiter_params)
        format.html { redirect_to @waiter, notice: 'Waiter was successfully updated.' }
        format.json { render :show, status: :ok, location: @waiter }
      else
        format.html { render :edit }
        format.json { render json: @waiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waiters/1
  # DELETE /waiters/1.json
  def destroy
    @waiter.destroy
    respond_to do |format|
      format.html { redirect_to waiters_url, notice: 'Waiter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waiter
      @waiter = Waiter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waiter_params
      params.require(:waiter).permit(:name)
    end
end

app/helpers/waiters_helper.rb
module WaitersHelper
end

app/views/waiters/_form.html.erb
<%= simple_form_for(@waiter) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/waiters/edit.html.erb
<h1>Editing Waiter</h1>

<%= render 'form', waiter: @waiter %>

<%= link_to 'Show', @waiter %> |
<%= link_to 'Back', waiters_path %>

app/views/waiters/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container bg-dark cont">
  <div class="row">
    <div class="col-sm-10 offset-sm-1">
      <h1 class="display-4 text-white"> Garçons </h1>

      <table class="table table-striped table-hover table-light mt-3">
        <thead>
          <tr>
            <th>Nome</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @waiters.each do |waiter| %>
            <tr>
              <td><%= waiter.name %></td>
              <td><%= link_to waiter, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
                <i class="far fa-trash-alt"></i>
              <%end%>
              <td><%= link_to edit_waiter_path(waiter), class: "btn btn-primary" do %>
                <i class="far fa-edit"></i>
              <%end%>
              <td><%= link_to waiter_path(waiter), class: "btn btn-success" do %>
                <i class="far fa-eye"></i>
              <%end%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Novo Garçom', new_waiter_path(), class: "btn btn-info" %>
    </div>
  </div>
</div>

app/views/waiters/new.html.erb
<h1>New Waiter</h1>

<%= render 'form', waiter: @waiter %>

<%= link_to 'Back', waiters_path %>

app/views/waiters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @waiter.name %>
</p>

<%= link_to 'Edit', edit_waiter_path(@waiter) %> |
<%= link_to 'Back', waiters_path %>