config/routes.rb
Rails.application.routes.draw do
  get 'requests/tables/:table_id', to: 'requests#table_requests', as: 'table_requests'
  get 'items/menus/:menu_id', to: 'items#items_by_menu', as: 'menu_items'
  get 'tables/:id/bill', to: 'tables#generate_bill', as: 'generate_bill'
  post 'tables/waiters/', to:  'tables#waiter_exists', as: 'waiter_exists'
  resources :waiters
  resources :tables do
    get '/bill', to: 'tables#generate_bill', as: 'generate_bill'
  end
  resources :items
  resources :menus
  resources :requests do
    patch '/amounts', to: 'requests#create_amounts'
    get '/amounts/all', to: 'requests#find_amounts'
    delete '/amounts/:id/delete', to: 'requests#delete_amount'
  end
  resources :customers
  devise_for :users
  root 'tables#index'
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :edit, :update, :destroy,:generate_bill]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
  end

  def generate_bill
    requests = @table.requests

    msg = "Saint's Meal - #{Time.now}\n\n"
    requests.each do |request|
      bill = []
      msg += "Cliente: #{Customer.find(request.customer_id).name}, CPF: #{Customer.find(request.customer_id).CPF}\n\n\n"
      msg += "Garçom: #{Waiter.find(request.waiter_id).name}\n\n"
      msg += "Pedidos:\n"
      request.amounts.each do |amount|
        msg += "#{Item.find(amount.item_id).name}  ----> \t x#{amount.amount}\n"
        bill << Item.find(amount.item_id).price * amount.amount
      end
      bill = bill.sum().round(2)
      msg += "\n|----------------------------------|\n"
      msg += "          Total: #{bill}            \n"
      msg += "|----------------------------------|"

      msg += "\n\n\n--------------------- DESTAQUE AQUI ------------------------\n\n\n"

    end
    send_data msg, filename: "Conta.txt"
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url, notice: 'Table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:number)
    end
end

app/helpers/tables_helper.rb
module TablesHelper
    def opened_at(table)
        table.requests.pluck(:created_at).sort().first.strftime("%d/%m/%Y %I:%M") if table.requests.present?
    end

    def count_requests(table)
        requests = table.requests
        bill = []
        requests.map(&:amounts).each do |amount|
            amount.each do |requested_item|
                bill << requested_item.amount * Item.find(requested_item.item_id).price
            end
        end
        bill.sum().round(2)
    end
end

app/views/tables/_form.html.erb
<%= simple_form_for(@table) do |f| %>
  <div class='container'>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :number %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing Table</h1>

<%= render 'form', table: @table %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container bg-dark cont">
  <div class="row">
    <div class="col-sm-10 offset-sm-1">
      <h1 class="display-4 text-white"> Mesas </h1>

      <table class="table table-striped table-hover table-light mt-3">
        <thead>
          <tr>
            <th>Número</th>
            <th>Abertura</th>
            <th>Valor Atual</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @tables.each do |table| %>
            <tr>
              <td><%= table.number %></td>
              <td><%= opened_at(table) %></td>
              <td>R$<%= count_requests(table) %></td>
              <td><%= link_to table, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
                <i class="far fa-trash-alt"></i>
              <%end%>
              &nbsp;&nbsp;
              <%= link_to edit_table_path(table), class: "btn btn-primary" do %>
                <i class="far fa-edit"></i>
              <%end%>
              &nbsp;&nbsp;
              <%= link_to table_path(table), class: "btn btn-success" do %>
                <i class="far fa-eye"></i>
              <%end%>
              &nbsp;&nbsp;
              <% if table.try(:requests).present? %>
                <%= link_to table_requests_path(table), class: "btn btn-default", style: "color: red;" do %>
                  <i class="far fa-bell"></i>
                <%end%>
                &nbsp;&nbsp;
                <%= link_to generate_bill_path(table), class: "btn btn-warning" do %>
                  <i class="fas fa-wallet"></i>
                <%end%>
              <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Nova Mesa', new_table_path(), class: "btn btn-info" %>
    </div>
  </div>
</div>

app/views/tables/new.html.erb
<div class='container' style="height: calc(100vh - 135px)">
    <h1>New Table</h1>

    <%= render 'form', table: @table %>

    <%= link_to 'Back', tables_path %>
</div>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>