config/routes.rb
Rails.application.routes.draw do
  get 'requests/tables/:table_id', to: 'requests#table_requests', as: 'table_requests'
  get 'items/menus/:menu_id', to: 'items#items_by_menu', as: 'menu_items'
  get 'tables/:id/bill', to: 'tables#generate_bill', as: 'generate_bill'
  post 'tables/waiters/', to:  'tables#waiter_exists', as: 'waiter_exists'
  resources :waiters
  resources :tables do
    get '/bill', to: 'tables#generate_bill', as: 'generate_bill'
  end
  resources :items
  resources :menus
  resources :requests do
    patch '/amounts', to: 'requests#create_amounts'
    get '/amounts/all', to: 'requests#find_amounts'
    delete '/amounts/:id/delete', to: 'requests#delete_amount'
  end
  resources :customers
  devise_for :users
  root 'tables#index'
end

app/views/layouts/_footer.html.erb
<div style="height:60px;background-color:#000;">
    <%= image_tag("logofooter.png", size:"60", style:"margin-left:48%") %>
</div>

app/views/layouts/_header.html.erb
<div class="transparent"></div>
<div id="side-menu">
    <div id="slide-menu-header">
        <% if user_signed_in? %>
            <h5 class="lead">Olá, <%= current_user.email %></h5>
        <% end %>
    </div>
    <div id="slide-menu-body">
        <ul class="mt-3">
            <li class="lead"><%= link_to "Clientes", customers_path()%></li>
            <li class="lead"><%= link_to "Pedidos", requests_path()%></li>
            <li class="lead"><%= link_to "Mesas", tables_path()%></li>
            <li class="lead"><%= link_to "Cardápios", menus_path()%></li>
            <li class="lead"><%= link_to "Garçons", waiters_path()%></li>
            <% if user_signed_in? %>
                <li class="lead"><%= link_to "Sair", destroy_user_session_path(), method: :delete %></li>
            <% end %>
        </ul>
    </div>
</div>
<nav class="navbar">
    <div class="container">
        <div>
            <i class="fas fa-bars icone-menu"></i>
            <%= image_tag("saintsmeal.png", alt: "Logo", class: "logo mx-auto")%>
        </div>
    </div>
    
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaintsMeal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>

    <script>
        $(document).ready(function () {
          $('.icone-menu').click(function (e) { 
              e.preventDefault();
              $('.transparent').show()
              $('#side-menu').animate({
                  marginLeft: "0"
              }, 300)
          });

          $('.transparent').click(function (e) { 
              $('.transparent').hide()
              $('#side-menu').animate({
                  marginLeft: "-25%"
              }, 300)
          });
      });
    </script>

  </head>

  <body>
    <%= render partial: 'layouts/header', remote: true %>
    <%= yield %>
    <%= render partial: 'layouts/footer', remote: true %>
  </body>
</html>